name: instagram_clone
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0

  #cloud firestore
  cloud_firestore: ^4.5.0

  #Unique Identifier
  uuid: ^3.0.7

  #StateManagement
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6

  #Font Awesome for fonts
  font_awesome_flutter: ^10.4.0

  #authentication
  flutter_facebook_auth: ^5.0.8
  google_sign_in: ^6.0.2

  #ImagePicker
  image_picker: ^0.8.7+1
  image: ^4.0.15

  #VideoPicker
  video_thumbnail: ^0.5.3
  video_player: ^2.6.0

  #Internationalization
  intl: ^0.17.0
  
  #Json data Animation
  lottie: ^2.3.2
  
  share_plus: ^6.3.1
  url_launcher: ^6.1.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/animations/
   
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
